### ISSUE TITLE
Better link tracking

### ISSUE THREAD

**Issue by blmarket** [blmarket/lsp-md#4]
http links are waste of screen space - they are long, cryptic, but giving subtle value. (still I'd like to know which domain I'm going to - I'll like trust https://blmarket.net than http://iwillscamyou.com)

Currently my notes are mostly just putting those links in plain text:

```markdown
some title:
https?://domain/path#search
```

I'm wondering I can just hide most part of it during the simple navigation.

```markdown
[some title](~domain~)
```

and should allow `gx` on title part.

- [ ] can it be handled by language server protocol?
  - [ ] should I override `gx` command to achieve this?
- [ ] any existing vim/nvim plugin to handle this, regardless of using lsp?
